import "../globals.css";

export const dynamic = "force-dynamic";

import type { Metadata } from "next";
import { env } from "@/env";
import { getSession } from "@/lib/auth";

import Header from "@/components/root/header";
import ChatProvider from "@/components/chat/_provider/chat.provider";
import AuthContextProvider from "@/lib/context/auth.context";
import ColorEqualizer from "@/components/ColorEqualizer";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Trans & Dance",
  description: "Generated by 3 smart asses",
};

export default async function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en">
      <body className="bg-background">
        <ColorEqualizer />
        <Toaster position="bottom-right" />

        <AuthContextProvider session={session!} url={env.API_URL}>
          <ChatProvider>
            <div>
              <div className="flex flex-col gap-4 min-h-screen min-w-screen bg-neutral-900">
                <Header />
                <div className="flex items-center p-4 w-full">
                  <div className="lg:w-3/4 lg:mx-auto w-full">{children}</div>
                </div>
              </div>
            </div>
          </ChatProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
